-- DROP TABLE IF EXISTS users;
CREATE TABLE users(
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    username TEXT UNIQUE NOT NULL,
    password TEXT NOT NULL,
    email VARCHAR ( 255 ) UNIQUE NOT NULL,
    fname VARCHAR ( 255 ) NOT NULL,
    lname VARCHAR ( 255 ) NOT NULL,
    address VARCHAR ( 255 ) NOT NULL,
    created_on TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    debt DOUBLE NOT NULL DEFAULT 0
);
