CREATE DATABASE IF NOT EXISTS mydatabase;
USE mydatabase;
DROP TABLE IF EXISTS users;
CREATE TABLE users(id INT AUTO_INCREMENT PRIMARY KEY,username VARCHAR(255) NOT NULL,password VARCHAR(255) NOT NULL,email VARCHAR(255) NOT NULL,fname VARCHAR(255) NOT NULL,lname VARCHAR(255) NOT NULL,address VARCHAR(255) NOT NULL,created_on TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,debt int NOT NULL,UNIQUE (username),UNIQUE (email));